version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/FrontEnd/ndgradgate"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
