name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for opening your first issue in this repository! We appreciate your contributions and will try to respond as soon as possible.'
          pr-message: 'Thank you for submitting your first pull request! Our team will review it shortly.'
